spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_database
    username: root
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 3000
  servlet:
    context-path: /api/v1
jwt:
  signerKey: zN/gkNC3dQIrDfQQ2Yyv9zo/OyEc6t/BjI20zDPNY+v2i1W69TVL2rJNJkXsGLi7
  valid-duration: 300
  refreshable-duration: 604800
